version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: dev_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Froydbanatao-03
      MYSQL_DATABASE: mydb
      MYSQL_USER: root
      MYSQL_PASSWORD: Froydbanatao-03
    ports:
      - "8888:8080"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
